from .brand_guidelines import (
    ADG_PALETTE,
    ALLOWED_SLIDE_COLORS,
    BRAND_FONT,
    SECTION_NUMBER_FONT_SIZE,
    SECTION_SUBTITLE_FONT_SIZE,
    SECTION_TITLE_FONT_SIZE,
    SUBTITLE_COLOR,
    SUBTITLE_FONT_SIZE,
    TITLE_COLOR,
    TITLE_FONT_SIZE,
)

__all__ = [
    "ADG_PALETTE",
    "ALLOWED_SLIDE_COLORS",
    "BRAND_FONT",
    "SECTION_NUMBER_FONT_SIZE",
    "SECTION_SUBTITLE_FONT_SIZE",
    "SECTION_TITLE_FONT_SIZE",
    "SUBTITLE_COLOR",
    "SUBTITLE_FONT_SIZE",
    "TITLE_COLOR",
    "TITLE_FONT_SIZE",
]
